[pytest]
log_cli = true
log_cli_level = INFO
log_format = %(message)s

markers =
    smoke: основные проверки критичного функционала
    regression: регрессионные проверки
    negative: негативные проверки